version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd:latest
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:latest
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - front_net
      - backend

networks:
  backend:
  frontend:


