version: '3.3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - monitoring

  elasticsearch:
    image: elasticsearch:5
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - monitoring

  kibana:
    image: kibana:5
    ports:
      - "5601:5601"
    networks:
      - monitoring

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - monitoring
      - front_net
      - back_net

networks:
  monitoring:
    ipam:
      driver: default
      config:
        - subnet: 10.0.3.0/24

  front_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
