version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
          - post_db
          - comment_db

  ui:
    # build: ./ui
    image: ${USERNAME}/ui:${UIVERSION}
    ports:
      - 9292:9292/tcp
    networks:
      - frontend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    # build: ./post-py
    image: ${USERNAME}/post:${POSTVERSION}
    networks:
      - backend
      - frontend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  comment:
    # build: ./comment
    image: ${USERNAME}/comment:${COMMENTVERSION}
    networks:
      - backend
      - frontend
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

volumes:
  post_db:

networks:
  backend:
    ipam:
      config:
        - subnet: 192.168.100.0/24
  frontend:
    ipam:
      config:
        - subnet: 192.168.10.0/24



